"use strict";
let miNumero = 10;
miNumero = 10 + 10;
miNumero = 2.5;
console.log(miNumero);
let booleano = true;
booleano = false;
//booleano = 3;
//booleano = false;
let encendido;
encendido = true;
console.log("encendido es", encendido);
encendido = true && false;
console.log(encendido);
