var normalx = 'hola';
normalx = 10;
normalx = true;
var usuario = 20;
console.log(normalx);
var nombre = 'Greys';
nombre = 'Alexa';
console.log(nombre);
var value;
console.log(value);
value = true;
value = 10;
value = 'holiwis';
value = [];
value = {};
value = Math.random;
value = null;
value = undefined;
console.log(value);
var miValor;
console.log("Tipo unknown", miValor);
var value1 = miValor;
var value2 = miValor;
//let value3: boolean = miValor;
var edad = 20;
console.log('Mi edad es:', edad);
console.log('Mi edad es:' + edad);
var sueldo = 123.456;
var total = Number('123'); //cast
console.log('Sueldo: ', sueldo);
console.log('Total: ', total);
var personaje = 'Mordecai el pájaro azul';
var otroPersonaje = "Rigby la ardilla";
var otroOtroPersonaje = "Papaleta y ".concat(personaje);
console.log(otroOtroPersonaje);
var heroe = "Spiderman's House";
console.log(heroe);
console.log(heroe.toUpperCase());
var vengador;
vengador = 'Ironman';
console.log(vengador.charAt(4).toUpperCase());
vengador = 150.55;
//Redondeo a un decimal
console.log('El redondeo de 150.55 a 1 decimal es:', vengador.toFixed(1));
console.log(vengador.toFixed(1));
// Eliminado el casting incorrecto
var personas = ['Peter', 'Tony', 'Strange'];
console.log(personas);
console.log(personas[0]);
console.log(personas[2]); // Cambié a un índice válido
personas.push('Jose');
console.log(personas);
var numeros = [1, 2, 3, 4, 5];
var numeros2 = [6, 7, 8, 9, 10];
numeros2.push(11);
var numerosReverse = numeros.reverse();
console.log(numeros, numeros2, numerosReverse);
document.getElementById('contenedorNumeros').innerHTML = "<h2>N\u00FAmeros:</h2> <p>".concat(numeros.join(', '), "</p>");
document.getElementById('contenedorNumeros2').innerHTML = "<h2>N\u00FAmeros 2:</h2> <p>".concat(numeros2.join(', '), "</p>");
document.getElementById('contenedorNumerosR').innerHTML = "<h2>N\u00FAmeros al rev\u00E9s:</h2> <p>".concat(numerosReverse.join(', '), "</p>");
var miArray = ['Renata', 20, 35, 'Saul', 20, 'Lucas', 12];
console.log(miArray);
var miArray2 = ['Hulk', 'Thor', 10, 'Dr. strange'];
console.log(miArray2);
var miArray3 = [true, 10, 'Jose', 20.5];
console.log(miArray3);
var miArray4 = [];
console.log(miArray4);
miArray4.push(10);
miArray4.push(20);
miArray4.push(30);
var miArray5 = [];
miArray5.push('Arcoiris');
miArray5.push(20);
miArray5.push(true);
miArray5.push('https://i.pinimg.com/474x/2f/dc/0a/2fdc0a746c99eb9a0b486ac0950c80c6.jpg');
miArray5.push('Jake');
miArray5.push(25);
miArray5.push('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR38X4moy3jvdb44PAPjx6FrPYGaQUAnwsUTw&s');
